export {default as Home} from './Home/Home'
export {default as Details} from './Details/Details'
export {default as Search} from './Search/Search'
export {default as Seats} from './Seats/Seats'
export {default as Ticket} from './Ticket/Ticket'
export {default as User} from './User/User'